package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "resumes")
public class Resume {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  public String name;

  public String birthDate;

  public String gender;
  
  public String jobTitle;
  
  public String degree;
  
  public String reshteTahsili;
  
  public String sabeghe;
  
  public String zamineKari;
  
  public String phone_number;
  
  public String email;
  
  public String HowDidYouMeetUs;
  
  public String description;
  
  public String resume;  
  
  
  public String teamNumber;
  
  public String beginningDate;
  
  public String takhasos;
  
  
  
  
  
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  public Resume() { }

  public Resume(long id) { 
    this.id = id;
  }
  
  public Resume(String name, String birthDate,String gender,String jobTitle,String degree,String reshteTahsili,String sabeghe,String zamineKari,String phone_number,String email,String HowDidYouMeetUs,String description,String resume) {
    this.name = name;
    this.birthDate = birthDate;
    this.gender = gender;
    this.jobTitle = jobTitle;
    this.degree=degree;
    this.reshteTahsili=reshteTahsili;
    this.sabeghe=sabeghe;
    this.zamineKari=zamineKari;
    this.phone_number=phone_number;
    this.email=email;
    this.HowDidYouMeetUs=HowDidYouMeetUs;
    this.description=description;
    this.resume=resume;

  }
  
  public Resume(String name, String teamNumber,String beginnigDate,String sabeghe,String takhasos,String zamineKari,String phone_number,String email,String HowDidYouMeetUs,String description,String resume) {
	    this.name = name;
	    this.teamNumber = teamNumber;
	    this.beginningDate = beginningDate;
	    this.sabeghe = sabeghe;
	    this.takhasos=takhasos;
	    this.zamineKari = zamineKari;
	    this.phone_number=phone_number;
	    this.email=email;
	    this.description=description;
	    this.resume=resume;
	    this.HowDidYouMeetUs=HowDidYouMeetUs;
	  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public long getid() {
    return id;
  }
  
  public void setid(long id) {
    this.id = id;
  }
  
  

} // class Resume
