package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "resumes")
public class Resume {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int id;
  
  @NotNull
  public int owner_id;
  
  public String type;

  public String jobTitle;
 
  public String sabeghe;
  
  public String description;
  
  public String resume_file;  
  
  public int teamNumber;
  
  public String takhasos;
  
  
  
  
  
  
  
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  public Resume() { }

  public Resume(int id) { 
    this.id = id;
  }
  
  public Resume(int owner_id,String jobTitle,String sabeghe,String description,String resume_file,String takhasos,String type) {
    this.owner_id=owner_id;
	this.jobTitle = jobTitle;
    this.sabeghe=sabeghe;
    this.description=description;
    this.resume_file=resume_file;
    this.type=type;
    this.takhasos=takhasos;

  }
  
  public Resume(int owner_id,int teamNumber,String sabeghe,String takhasos,String description,String resume_file,String type) {
	    this.owner_id=owner_id;
	  	this.teamNumber = teamNumber;
	    this.sabeghe = sabeghe;
	    this.takhasos=takhasos;
	    this.description=description;
	    this.resume_file=resume_file;
	    this.type=type;
	  }

  // Getter and setter methods

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }
  
  

} // class Resume
